[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    nextConfigDir = "."
    forceSsr = true
    nodeVersion = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200  force = true
